apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-member2
  ownerReferences:
    - apiVersion: apps/v1
      kind: Job
      name: job-3-1
      uid: uid-3-1
    - apiVersion: batch.volcano.sh/v1alpha1
      kind: Job
      name: example-hyperjob-taskb-0
      uid: 7a0fda34-b9da-415a-8ed8-7e741596b136
data:
  "jobstart_hccl.json": '{
    "status": "completed",
    "version": "1.4",
    "data_version": 6,
    "server_count": "2",
    "server_list": [
      {
      "server_id": "222.222.222.1",
      "device": [
        {
        "device_id": "0",
        "super_device_id": "0",
        "device_ip": "10.0.0.0",
        "rank_id": "0",
        "dpu_ip": "0.0.0.0",
	    "numa_id": "0"
        },{
        "device_id": "1",
        "super_device_id": "1",
        "device_ip": "10.0.0.1",
        "rank_id": "1",
        "dpu_ip": "0.0.0.0",
	    "numa_id": "0"
        }]
      },{
      "server_id": "222.222.222.2",
      "device": [
        {
        "device_id": "0",
        "super_device_id": "2",
        "device_ip": "10.0.0.0",
        "rank_id": "0",
        "dpu_ip": "0.0.0.0",
	    "numa_id": "0"
        },{
        "device_id": "1",
        "super_device_id": "3",
        "device_ip": "10.0.0.1",
        "rank_id": "1",
        "dpu_ip": "0.0.0.0",
	    "numa_id": "0"
        }]
      },{
      "server_id": "222.222.222.3",
      "device": [
        {
        "device_id": "0",
        "super_device_id": "2",
        "device_ip": "10.0.0.0",
        "rank_id": "0",
        "dpu_ip": "0.0.0.0",
	    "numa_id": "0"
        },{
        "device_id": "1",
        "super_device_id": "3",
        "device_ip": "10.0.0.1",
        "rank_id": "1",
        "dpu_ip": "0.0.0.0",
	    "numa_id": "0"
        }]
      }],
    "super_pod_list": [
      {
      "super_pod_id": "hypernode-0",
      "server_list": [{"server_id": "222.222.222.1"},{"server_id": "222.222.222.3"}]
      },{
      "super_pod_id": "hypernode-1",
      "server_list": [{"server_id": "222.222.222.2"}]
      }],
    "cluster_list": [
      {
      "cluster_id": "0",
      "az_id": "az1",
      "region_id": "cn-north-7",
      "super_pod_list": [{
        "super_pod_id": "hypernode-0"
        },{
        "super_pod_id": "hypernode-1"
        }]
      }]      
    }'
